language: python

env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=flake8
    - TOXENV=coverage
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
          env: TOXENV=py37

install:
    - travis_retry pip install tox

script:
    - tox
